"use client";

import { ContactProfileSchema, ContactVerificationRequestResponseSchema, type ContactProfile, type ContactVerificationChannel, type NotificationPreferences } from "@rama/contracts";
import { BellRing, CheckCircle2, CircleAlert, KeyRound, LockKeyhole, Mail, MessageSquareText, Phone, Save, ShieldCheck } from "lucide-react";
import { useState } from "react";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import type { Locale } from "@/lib/i18n";

type Props = { initialProfile: ContactProfile | null; locale: Locale };
type Notice = { kind: "error" | "success"; text: string } | null;
const defaults: NotificationPreferences = { caseUpdatesInApp: true, caseUpdatesEmail: false, caseUpdatesSms: false, allowInAppFallback: true };

const copy = {
  en: {
    skip:"Skip to protected contact settings",brand:"RAMA",secure:"Protected customer settings",language:"العربية",advisor:"Advisor handoff",inbox:"Notifications",
    title:"Keep contact details outside the decision case.",intro:"RAMA encrypts contact values at rest. Advisors see delivery outcomes—not your email address or phone number.",privacy:"Saving a new set replaces the existing contact points. Stored values are returned only as masks.",
    points:"Protected contact points",pointsHelp:"Use an international phone number beginning with +. A changed value must be verified again.",email:"Email address",phone:"Phone (E.164)",emailPlaceholder:"name@example.com",phonePlaceholder:"+971501234567",save:"Save contact points",saving:"Saving…",saved:"Contact points encrypted and saved.",replace:"Replace stored contact points",
    verification:"Verification",verify:"Send code",sending:"Sending…",verified:"Verified",unverified:"Unverified",pending:"Code sent",code:"Six-digit code",confirm:"Confirm code",confirming:"Confirming…",verifiedMessage:"Contact point verified.",expires:"Code expires",development:"Development verification code",
    preferences:"Notification preferences",preferencesHelp:"In-app case updates stay enabled. External channels require a saved contact point and successful verification.",inApp:"In-app case updates",byEmail:"Email case updates",bySms:"SMS case updates",fallback:"Fall back to in-app delivery when the selected external channel is unavailable",savePreferences:"Save preferences",preferencesSaved:"Notification preferences updated.",failed:"The protected-contact update failed. Refresh if another session changed it.",audit:"Versioned activity",version:"Profile version",
  },
  ar: {
    skip:"الانتقال إلى إعدادات الاتصال المحمية",brand:"راما",secure:"إعدادات عميل محمية",language:"English",advisor:"تسليم المستشار",inbox:"الإشعارات",
    title:"احتفظ ببيانات الاتصال خارج حالة القرار.",intro:"تشفّر راما قيم الاتصال أثناء التخزين. يرى المستشار نتيجة التسليم وليس بريدك الإلكتروني أو رقم هاتفك.",privacy:"يستبدل حفظ مجموعة جديدة نقاط الاتصال الحالية. لا تُعاد القيم المخزنة إلا بشكل مخفي.",
    points:"نقاط اتصال محمية",pointsHelp:"استخدم رقماً دولياً يبدأ بعلامة +. يجب التحقق مجدداً من أي قيمة تتغير.",email:"البريد الإلكتروني",phone:"الهاتف (E.164)",emailPlaceholder:"name@example.com",phonePlaceholder:"+971501234567",save:"حفظ نقاط الاتصال",saving:"جارٍ الحفظ…",saved:"تم تشفير نقاط الاتصال وحفظها.",replace:"استبدال نقاط الاتصال المحفوظة",
    verification:"التحقق",verify:"إرسال الرمز",sending:"جارٍ الإرسال…",verified:"تم التحقق",unverified:"غير متحقق",pending:"تم إرسال الرمز",code:"رمز من ستة أرقام",confirm:"تأكيد الرمز",confirming:"جارٍ التأكيد…",verifiedMessage:"تم التحقق من نقطة الاتصال.",expires:"انتهاء الرمز",development:"رمز التحقق للتطوير",
    preferences:"تفضيلات الإشعارات",preferencesHelp:"تبقى تحديثات الحالة داخل التطبيق مفعلة. تتطلب القنوات الخارجية نقطة اتصال محفوظة ومتحققاً منها.",inApp:"تحديثات الحالة داخل التطبيق",byEmail:"تحديثات الحالة بالبريد",bySms:"تحديثات الحالة برسالة نصية",fallback:"الرجوع إلى التسليم داخل التطبيق عند عدم توفر القناة الخارجية المحددة",savePreferences:"حفظ التفضيلات",preferencesSaved:"تم تحديث تفضيلات الإشعارات.",failed:"تعذر تحديث الاتصال المحمي. حدّث الصفحة إذا غيرته جلسة أخرى.",audit:"نشاط محفوظ بالإصدارات",version:"إصدار الملف",
  },
} as const;

export function CustomerContactSettings({ initialProfile, locale }: Props) {
  const t=copy[locale]; const rtl=locale==="ar";
  const [profile,setProfile]=useState(initialProfile); const [email,setEmail]=useState(""); const [phone,setPhone]=useState("");
  const [preferences,setPreferences]=useState<NotificationPreferences>(initialProfile?.preferences??defaults);
  const [challenge,setChallenge]=useState<{channel:ContactVerificationChannel;code:string;expiresAt:string}|null>(null); const [code,setCode]=useState("");
  const [busy,setBusy]=useState<"points"|"preferences"|"request"|"confirm"|null>(null); const [notice,setNotice]=useState<Notice>(null);

  const savePoints=async()=>{setBusy("points");setNotice(null);try{const response=await fetch("/api/customer/contact-profile/points",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({expectedVersion:profile?.version??null,locale,email:email.trim()||null,phoneE164:phone.trim()||null})});if(!response.ok)throw new Error(String(response.status));const next=ContactProfileSchema.parse(await response.json());setProfile(next);setPreferences(next.preferences);setEmail("");setPhone("");setChallenge(null);setNotice({kind:"success",text:t.saved});}catch{setNotice({kind:"error",text:t.failed});}finally{setBusy(null)}};
  const savePreferences=async()=>{if(!profile)return;setBusy("preferences");setNotice(null);try{const response=await fetch("/api/customer/contact-profile/preferences",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({expectedVersion:profile.version,preferences})});if(!response.ok)throw new Error(String(response.status));const next=ContactProfileSchema.parse(await response.json());setProfile(next);setPreferences(next.preferences);setNotice({kind:"success",text:t.preferencesSaved});}catch{setNotice({kind:"error",text:t.failed});}finally{setBusy(null)}};
  const request=async(channel:ContactVerificationChannel)=>{if(!profile)return;setBusy("request");setNotice(null);try{const response=await fetch("/api/customer/contact-profile/verification/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({expectedVersion:profile.version,channel})});if(!response.ok)throw new Error(String(response.status));const result=ContactVerificationRequestResponseSchema.parse(await response.json());setProfile(result.profile);setChallenge({channel,code:result.developmentCode??"",expiresAt:result.expiresAt});setCode(result.developmentCode??"");}catch{setNotice({kind:"error",text:t.failed});}finally{setBusy(null)}};
  const confirm=async()=>{if(!profile||!challenge)return;setBusy("confirm");setNotice(null);try{const response=await fetch("/api/customer/contact-profile/verification/confirm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({expectedVersion:profile.version,channel:challenge.channel,code})});if(!response.ok)throw new Error(String(response.status));const next=ContactProfileSchema.parse(await response.json());setProfile(next);setPreferences(next.preferences);setChallenge(null);setCode("");setNotice({kind:"success",text:t.verifiedMessage});}catch{setNotice({kind:"error",text:t.failed});}finally{setBusy(null)}};
  const toggle=(key:keyof NotificationPreferences,value:boolean)=>setPreferences((current)=>({...current,[key]:value}));

  return <div className="communicationsApp" dir={rtl?"rtl":"ltr"} lang={locale}><a className="skipLink" href="#contact-main">{t.skip}</a><header className="communicationsHeader"><div><a className="brand" href={`/${locale}/settings/contact`}><span className="brandMark" aria-hidden="true">R</span>{t.brand}</a><span><LockKeyhole aria-hidden="true" />{t.secure}</span><nav><a href={`/${locale}/advisor`}>{t.advisor}</a><a href={`/${locale}/notifications`}>{t.inbox}</a><a href={`/${locale==="en"?"ar":"en"}/settings/contact`} lang={locale==="en"?"ar":"en"}>{t.language}</a></nav></div></header><main className="communicationsFrame" id="contact-main"><section className="communicationsIntro"><div><p className="eyebrow">RAMA / PROTECTED CONTACT</p><h1>{t.title}</h1></div><div><p>{t.intro}</p><span><ShieldCheck aria-hidden="true" />{t.privacy}</span></div></section>
    {notice&&<Alert className="communicationsNotice" variant={notice.kind==="error"?"destructive":"default"}><CircleAlert aria-hidden="true" /><AlertTitle>{notice.text}</AlertTitle></Alert>}
    <div className="communicationsGrid"><Card className="contactCard"><CardHeader><Mail aria-hidden="true" /><CardTitle><h2>{profile?t.replace:t.points}</h2></CardTitle><CardDescription>{t.pointsHelp}</CardDescription></CardHeader><CardContent><div className="contactFields"><label htmlFor="contact-email"><span>{t.email}</span><Input id="contact-email" type="email" autoComplete="email" value={email} placeholder={profile?.email?.masked??t.emailPlaceholder} onChange={(event)=>setEmail(event.target.value)} /></label><label htmlFor="contact-phone"><span>{t.phone}</span><Input id="contact-phone" type="tel" autoComplete="tel" dir="ltr" value={phone} placeholder={profile?.phone?.masked??t.phonePlaceholder} onChange={(event)=>setPhone(event.target.value)} /></label></div><Button size="lg" onClick={savePoints} disabled={busy!==null||(!email.trim()&&!phone.trim())}><Save data-icon="inline-start" aria-hidden="true" />{busy==="points"?t.saving:t.save}</Button></CardContent></Card>
      <Card className="contactCard"><CardHeader><KeyRound aria-hidden="true" /><CardTitle><h2>{t.verification}</h2></CardTitle><CardDescription>{profile?`${t.version}: ${profile.version}`:t.pointsHelp}</CardDescription></CardHeader><CardContent>{profile?<div className="verificationList"><VerificationPoint icon={Mail} label={t.email} point={profile.email} text={t} onRequest={()=>request("email")} busy={busy!==null}/><VerificationPoint icon={Phone} label={t.phone} point={profile.phone} text={t} onRequest={()=>request("sms")} busy={busy!==null}/>{challenge&&<div className="verificationChallenge"><Alert><MessageSquareText aria-hidden="true" /><AlertTitle>{challenge.channel==="email"?t.email:t.phone}</AlertTitle><AlertDescription>{t.expires}: {new Intl.DateTimeFormat(locale,{timeStyle:"short"}).format(new Date(challenge.expiresAt))}{challenge.code&&<><br/>{t.development}: <code>{challenge.code}</code></>}</AlertDescription></Alert><label htmlFor="verification-code"><span>{t.code}</span><Input id="verification-code" inputMode="numeric" maxLength={6} value={code} onChange={(event)=>setCode(event.target.value.replace(/\D/g,""))}/></label><Button onClick={confirm} disabled={busy!==null||code.length!==6}><CheckCircle2 data-icon="inline-start" aria-hidden="true" />{busy==="confirm"?t.confirming:t.confirm}</Button></div>}</div>:<p>{t.pointsHelp}</p>}</CardContent></Card>
    </div>
    {profile&&<Card className="preferencesCard"><CardHeader><BellRing aria-hidden="true" /><CardTitle><h2>{t.preferences}</h2></CardTitle><CardDescription>{t.preferencesHelp}</CardDescription></CardHeader><CardContent><div className="preferenceChoices"><Preference id="pref-in-app" label={t.inApp} checked disabled onChange={()=>{}}/><Preference id="pref-email" label={t.byEmail} checked={preferences.caseUpdatesEmail} disabled={!profile.email} onChange={(value)=>toggle("caseUpdatesEmail",value)}/><Preference id="pref-sms" label={t.bySms} checked={preferences.caseUpdatesSms} disabled={!profile.phone} onChange={(value)=>toggle("caseUpdatesSms",value)}/><Preference id="pref-fallback" label={t.fallback} checked={preferences.allowInAppFallback} onChange={(value)=>toggle("allowInAppFallback",value)}/></div><Button size="lg" onClick={savePreferences} disabled={busy!==null}><Save data-icon="inline-start" aria-hidden="true" />{busy==="preferences"?t.saving:t.savePreferences}</Button><div className="contactAudit"><strong>{t.audit}</strong><span>{profile.auditTrail.length} · v{profile.version}</span></div></CardContent></Card>}
  </main></div>;
}

type Text=typeof copy.en|typeof copy.ar;
function VerificationPoint({icon:Icon,label,point,text:t,onRequest,busy}:{icon:typeof Mail;label:string;point:ContactProfile["email"];text:Text;onRequest:()=>void;busy:boolean}){return <div className="verificationPoint"><Icon aria-hidden="true"/><div><strong>{label}</strong><span>{point?.masked??"—"}</span></div>{point?<><Badge variant={point.status==="verified"?"secondary":"outline"}>{point.status==="verified"?t.verified:point.status==="verification_pending"?t.pending:t.unverified}</Badge>{point.status!=="verified"&&<Button variant="outline" onClick={onRequest} disabled={busy}>{t.verify}</Button>}</>:null}</div>}
function Preference({id,label,checked,disabled=false,onChange}:{id:string;label:string;checked:boolean;disabled?:boolean;onChange:(value:boolean)=>void}){return <label htmlFor={id}><Checkbox id={id} checked={checked} disabled={disabled} onCheckedChange={onChange}/><span>{label}</span></label>}
