"use client";

import { CustomerNotificationSchema, type CustomerNotification, type CustomerNotificationListResponse } from "@rama/contracts";
import { BellRing, Check, CircleAlert, LockKeyhole, MailCheck, ShieldCheck } from "lucide-react";
import { useState } from "react";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { Locale } from "@/lib/i18n";

type Props={initial:CustomerNotificationListResponse;locale:Locale};
const copy={
  en:{skip:"Skip to notifications",brand:"RAMA",secure:"Private notification inbox",language:"العربية",settings:"Contact settings",advisor:"Advisor handoff",title:"A private record of every advisor update.",intro:"Each item shows what RAMA attempted, where it was delivered and whether a fallback was used—without exposing protected contact values.",privacy:"Only structured message templates are accepted. Notifications expire with their decision case.",empty:"No notifications yet",emptyHelp:"Advisor updates and delivery recovery records will appear here.",unread:"Unread",read:"Read",mark:"Mark as read",marking:"Saving…",failed:"The notification changed or could not be updated.",requested:"Requested channel",delivered:"Delivered channel",reason:"Delivery result",retention:"Retained until",states:{queued:"Queued",retrying:"Retry scheduled",delivered:"Delivered",fallback_delivered:"Delivered in app",failed:"Delivery failed"},templates:{advisor_acknowledgement:"Your advisor has acknowledged the case.",information_request:"Your advisor needs additional structured information.",questions_answered:"Your property questions have been answered.",viewing_coordination:"Your advisor is coordinating the property viewing.",financing_follow_up:"Your advisor has a financing-readiness follow-up."}},
  ar:{skip:"الانتقال إلى الإشعارات",brand:"راما",secure:"صندوق إشعارات خاص",language:"English",settings:"إعدادات الاتصال",advisor:"تسليم المستشار",title:"سجل خاص لكل تحديث من المستشار.",intro:"يوضح كل عنصر ما حاولت راما تسليمه وأين وصل وما إذا استُخدم مسار بديل، دون كشف قيم الاتصال المحمية.",privacy:"تُقبل قوالب رسائل منظمة فقط. تنتهي الإشعارات مع حالة القرار.",empty:"لا توجد إشعارات بعد",emptyHelp:"ستظهر هنا تحديثات المستشار وسجلات استعادة التسليم.",unread:"غير مقروء",read:"مقروء",mark:"وضع علامة مقروء",marking:"جارٍ الحفظ…",failed:"تغير الإشعار أو تعذر تحديثه.",requested:"القناة المطلوبة",delivered:"قناة التسليم",reason:"نتيجة التسليم",retention:"الاحتفاظ حتى",states:{queued:"في قائمة الانتظار",retrying:"إعادة المحاولة مجدولة",delivered:"تم التسليم",fallback_delivered:"تم التسليم داخل التطبيق",failed:"فشل التسليم"},templates:{advisor_acknowledgement:"أقر المستشار باستلام الحالة.",information_request:"يحتاج المستشار إلى معلومات منظمة إضافية.",questions_answered:"تمت الإجابة عن أسئلتك حول العقار.",viewing_coordination:"ينسق المستشار معاينة العقار.",financing_follow_up:"لدى المستشار متابعة حول الجاهزية التمويلية."}},
} as const;

export function CustomerNotifications({initial,locale}:Props){const t=copy[locale];const rtl=locale==="ar";const [items,setItems]=useState(initial.items);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState(false);const unread=items.filter((item)=>item.deliveredChannel==="in_app"&&!item.readAt).length;
  const mark=async(item:CustomerNotification)=>{setBusy(item.id);setError(false);try{const response=await fetch(`/api/customer/notifications/${item.id}/read`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({expectedVersion:item.version})});if(!response.ok)throw new Error(String(response.status));const updated=CustomerNotificationSchema.parse(await response.json());setItems((current)=>current.map((value)=>value.id===updated.id?updated:value));}catch{setError(true)}finally{setBusy(null)}};
  return <div className="communicationsApp" dir={rtl?"rtl":"ltr"} lang={locale}><a className="skipLink" href="#notifications-main">{t.skip}</a><header className="communicationsHeader"><div><a className="brand" href={`/${locale}/notifications`}><span className="brandMark" aria-hidden="true">R</span>{t.brand}</a><span><LockKeyhole aria-hidden="true"/>{t.secure}</span><nav><a href={`/${locale}/advisor`}>{t.advisor}</a><a href={`/${locale}/settings/contact`}>{t.settings}</a><a href={`/${locale==="en"?"ar":"en"}/notifications`} lang={locale==="en"?"ar":"en"}>{t.language}</a></nav></div></header><main className="communicationsFrame" id="notifications-main"><section className="communicationsIntro"><div><p className="eyebrow">RAMA / NOTIFICATIONS</p><h1>{t.title}</h1></div><div><p>{t.intro}</p><span><ShieldCheck aria-hidden="true"/>{t.privacy}</span></div></section><div className="notificationSummary"><BellRing aria-hidden="true"/><span>{t.unread}</span><strong>{unread}</strong></div>{error&&<Alert variant="destructive" className="communicationsNotice"><CircleAlert aria-hidden="true"/><AlertTitle>{t.failed}</AlertTitle></Alert>}{items.length?<div className="notificationList">{items.map((item)=>{const inApp=item.deliveredChannel==="in_app";const label=inApp?(!item.readAt?t.unread:t.read):t.states[item.status];return <Card className={`notificationCard${!item.readAt&&inApp?" isUnread":""}`} key={item.id}><CardHeader><MailCheck aria-hidden="true"/><CardTitle><h2>{t.templates[item.template]}</h2></CardTitle><Badge variant={!item.readAt&&inApp?"secondary":"outline"}>{label}</Badge><CardDescription>{new Intl.DateTimeFormat(locale==="ar"?"ar-AE":"en-AE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.createdAt))}</CardDescription></CardHeader><CardContent><dl><div><dt>{t.requested}</dt><dd>{item.requestedChannel}</dd></div><div><dt>{t.delivered}</dt><dd>{item.deliveredChannel??"—"}</dd></div><div><dt>{t.reason}</dt><dd>{item.deliveryReason.replaceAll("_"," ")}</dd></div><div><dt>{t.retention}</dt><dd>{new Intl.DateTimeFormat(locale==="ar"?"ar-AE":"en-AE",{dateStyle:"medium"}).format(new Date(item.retentionUntil))}</dd></div></dl>{inApp&&!item.readAt&&<Button variant="outline" onClick={()=>mark(item)} disabled={busy!==null}><Check data-icon="inline-start" aria-hidden="true"/>{busy===item.id?t.marking:t.mark}</Button>}</CardContent></Card>})}</div>:<Alert className="notificationsEmpty"><BellRing aria-hidden="true"/><AlertTitle>{t.empty}</AlertTitle><AlertDescription>{t.emptyHelp}</AlertDescription></Alert>}</main></div>}
