packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  core-js-pure: set this to true or false
  esbuild: true
  msgpackr-extract: false
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - lucide-react@1.25.0

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@swc/core"
